# Indexing


In [8]:
import numpy as np

In [9]:
arr2 = np.random.randint(0, 100,(10,10))

In [10]:
arr2 

array([[ 6, 37, 81,  6, 87, 17,  5, 10,  1, 79],
       [91, 18, 48,  5, 16, 40, 69, 26, 40, 58],
       [62, 15, 24, 22, 88, 43, 23, 62,  4, 99],
       [40, 20, 59, 11, 46,  1, 69, 22, 38, 13],
       [31, 20, 45,  1, 89, 26, 56, 69, 37, 50],
       [59, 96, 27, 49, 78, 72, 40, 75, 62, 97],
       [ 1, 10, 89, 62, 59, 30,  1, 73, 93, 16],
       [49, 48, 97, 51, 14, 26, 38, 65,  0, 68],
       [71, 49, 22, 28,  2, 43,  0,  0,  0, 96],
       [51, 43, 13, 83,  8, 82, 98, 54,  0, 22]])

In [11]:
row  = 4
col = 5 

In [13]:
arr2[row, col]

np.int64(26)

In [14]:
arr2[4]

array([31, 20, 45,  1, 89, 26, 56, 69, 37, 50])

# how to print specific colummn


In [15]:
arr2[:,col]

array([17, 40, 43,  1, 26, 72, 30, 26, 43, 82])

In [17]:
arr2[:,5]

array([17, 40, 43,  1, 26, 72, 30, 26, 43, 82])

In [19]:
arr2[0:10]

array([[ 6, 37, 81,  6, 87, 17,  5, 10,  1, 79],
       [91, 18, 48,  5, 16, 40, 69, 26, 40, 58],
       [62, 15, 24, 22, 88, 43, 23, 62,  4, 99],
       [40, 20, 59, 11, 46,  1, 69, 22, 38, 13],
       [31, 20, 45,  1, 89, 26, 56, 69, 37, 50],
       [59, 96, 27, 49, 78, 72, 40, 75, 62, 97],
       [ 1, 10, 89, 62, 59, 30,  1, 73, 93, 16],
       [49, 48, 97, 51, 14, 26, 38, 65,  0, 68],
       [71, 49, 22, 28,  2, 43,  0,  0,  0, 96],
       [51, 43, 13, 83,  8, 82, 98, 54,  0, 22]])

In [20]:
arr2[0:10:3]

array([[ 6, 37, 81,  6, 87, 17,  5, 10,  1, 79],
       [40, 20, 59, 11, 46,  1, 69, 22, 38, 13],
       [ 1, 10, 89, 62, 59, 30,  1, 73, 93, 16],
       [51, 43, 13, 83,  8, 82, 98, 54,  0, 22]])

In [22]:
arr2[2:6, 3:7]# 2:6 is row and 3:7 is column

array([[22, 88, 43, 23],
       [11, 46,  1, 69],
       [ 1, 89, 26, 56],
       [49, 78, 72, 40]])

# Masking


In [29]:
arr2[arr2<=50]

array([ 6, 37,  6, 17,  5, 10,  1, 18, 48,  5, 16, 40, 26, 40, 15, 24, 22,
       43, 23,  4, 40, 20, 11, 46,  1, 22, 38, 13, 31, 20, 45,  1, 26, 37,
       50, 27, 49, 40,  1, 10, 30,  1, 16, 49, 48, 14, 26, 38,  0, 49, 22,
       28,  2, 43,  0,  0,  0, 43, 13,  8,  0, 22])